// /*
//  * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
//  * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
//  */
// package DellStore.ui.manager;

// /**
//  *
//  * @author docon
//  */
// public class banhangJPanel extends javax.swing.JPanel {

//     /**
//      * Creates new form banhangJPanel
//      */
//     public banhangJPanel() {
//         initComponents();
//     }

//     /**
//      * This method is called from within the constructor to initialize the form.
//      * WARNING: Do NOT modify this code. The content of this method is always
//      * regenerated by the Form Editor.
//      */
//     @SuppressWarnings("unchecked")
//     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//     private void initComponents() {

//         jPanel4 = new javax.swing.JPanel();
//         jPanel2 = new javax.swing.JPanel();
//         jScrollPane1 = new javax.swing.JScrollPane();
//         jTable1 = new javax.swing.JTable();
//         jPanel3 = new javax.swing.JPanel();
//         jScrollPane3 = new javax.swing.JScrollPane();
//         jTable3 = new javax.swing.JTable();
//         jButton9 = new javax.swing.JButton();
//         jPanel5 = new javax.swing.JPanel();
//         jScrollPane2 = new javax.swing.JScrollPane();
//         jTable2 = new javax.swing.JTable();
//         jTextField15 = new javax.swing.JTextField();
//         jButton5 = new javax.swing.JButton();
//         jPanel1 = new javax.swing.JPanel();
//         jPanel6 = new javax.swing.JPanel();
//         jLabel1 = new javax.swing.JLabel();
//         jLabel2 = new javax.swing.JLabel();
//         jTextField1 = new javax.swing.JTextField();
//         jTextField2 = new javax.swing.JTextField();
//         jPanel7 = new javax.swing.JPanel();
//         jLabel3 = new javax.swing.JLabel();
//         jLabel4 = new javax.swing.JLabel();
//         jLabel5 = new javax.swing.JLabel();
//         jLabel13 = new javax.swing.JLabel();
//         jLabel14 = new javax.swing.JLabel();
//         jLabel15 = new javax.swing.JLabel();
//         jComboBox2 = new javax.swing.JComboBox<>();
//         jLabel17 = new javax.swing.JLabel();
//         jTextField11 = new javax.swing.JTextField();
//         jLabel18 = new javax.swing.JLabel();
//         jTextField12 = new javax.swing.JTextField();
//         jLabel19 = new javax.swing.JLabel();
//         jTextField13 = new javax.swing.JTextField();
//         jTextField5 = new javax.swing.JTextField();
//         jTextField6 = new javax.swing.JTextField();
//         jTextField7 = new javax.swing.JTextField();
//         jTextField8 = new javax.swing.JTextField();
//         jTextField9 = new javax.swing.JTextField();
//         jButton6 = new javax.swing.JButton();
//         jButton7 = new javax.swing.JButton();
//         jButton2 = new javax.swing.JButton();
//         jButton4 = new javax.swing.JButton();

//         jPanel4.setBackground(new java.awt.Color(255, 255, 255));

//         jPanel2.setBackground(new java.awt.Color(255, 255, 255));
//         jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("HÓA ĐƠN"));

//         jTable1.setModel(new javax.swing.table.DefaultTableModel(
//             new Object [][] {
//                 {null, null, null, null, null},
//                 {null, null, null, null, null},
//                 {null, null, null, null, null},
//                 {null, null, null, null, null}
//             },
//             new String [] {
//                 "STT", "Mã hóa đơn", "Ngày Tạo", "Tên NV", "Trạng thái"
//             }
//         ));
//         jScrollPane1.setViewportView(jTable1);

//         javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
//         jPanel2.setLayout(jPanel2Layout);
//         jPanel2Layout.setHorizontalGroup(
//             jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel2Layout.createSequentialGroup()
//                 .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addGap(0, 9, Short.MAX_VALUE))
//         );
//         jPanel2Layout.setVerticalGroup(
//             jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel2Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addGap(0, 8, Short.MAX_VALUE))
//         );

//         jPanel3.setBackground(new java.awt.Color(255, 255, 255));
//         jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("GIỎ HÀNG"));

//         jTable3.setModel(new javax.swing.table.DefaultTableModel(
//             new Object [][] {
//                 {null, null, null, null, null, null, null},
//                 {null, null, null, null, null, null, null},
//                 {null, null, null, null, null, null, null},
//                 {null, null, null, null, null, null, null}
//             },
//             new String [] {
//                 "STT", "Mã SP", "Tên SP", "Đơn Giá", "Số Lượng", "Giảm Giá", "Thành Tiền"
//             }
//         ));
//         jScrollPane3.setViewportView(jTable3);

//         jButton9.setBackground(new java.awt.Color(255, 153, 102));
//         jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/xoa.png"))); // NOI18N

//         javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
//         jPanel3.setLayout(jPanel3Layout);
//         jPanel3Layout.setHorizontalGroup(
//             jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel3Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addComponent(jScrollPane3)
//                 .addContainerGap())
//             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
//                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                 .addComponent(jButton9)
//                 .addGap(66, 66, 66))
//         );
//         jPanel3Layout.setVerticalGroup(
//             jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
//                 .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                 .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
//         );

//         jPanel5.setBackground(new java.awt.Color(255, 255, 255));
//         jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Sản Phẩm"));

//         jTable2.setModel(new javax.swing.table.DefaultTableModel(
//             new Object [][] {
//                 {null, null, null, null, null, null, null, null, null, null},
//                 {null, null, null, null, null, null, null, null, null, null},
//                 {null, null, null, null, null, null, null, null, null, null},
//                 {null, null, null, null, null, null, null, null, null, null}
//             },
//             new String [] {
//                 "STT", "Mã SP", "Tên SP", "CPU", "Ram", "Card", "Ổ Cứng", "Hãng", "Giá Bán", "Số Lượng"
//             }
//         ));
//         jScrollPane2.setViewportView(jTable2);

//         jButton5.setBackground(new java.awt.Color(255, 153, 102));
//         jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/timkiem.png"))); // NOI18N
//         jButton5.setText("Tìm kiếm");

//         javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
//         jPanel5.setLayout(jPanel5Layout);
//         jPanel5Layout.setHorizontalGroup(
//             jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel5Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addComponent(jScrollPane2)
//                     .addGroup(jPanel5Layout.createSequentialGroup()
//                         .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addGap(4, 4, 4)
//                         .addComponent(jButton5)
//                         .addGap(0, 0, Short.MAX_VALUE)))
//                 .addContainerGap())
//         );
//         jPanel5Layout.setVerticalGroup(
//             jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
//                 .addContainerGap())
//         );

//         jPanel1.setBackground(new java.awt.Color(255, 255, 255));
//         jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("ĐƠN HÀNG"));

//         jPanel6.setBackground(new java.awt.Color(255, 255, 255));
//         jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin khách hàng"));

//         jLabel1.setText("SDT: ");

//         jLabel2.setText("Tên KH:");

//         javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
//         jPanel6.setLayout(jPanel6Layout);
//         jPanel6Layout.setHorizontalGroup(
//             jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel6Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addComponent(jLabel2)
//                     .addComponent(jLabel1))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                 .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addComponent(jTextField1)
//                     .addComponent(jTextField2))
//                 .addGap(92, 92, 92))
//         );
//         jPanel6Layout.setVerticalGroup(
//             jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel6Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jLabel1)
//                     .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jLabel2)
//                     .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addContainerGap(22, Short.MAX_VALUE))
//         );

//         jPanel7.setBackground(new java.awt.Color(255, 255, 255));
//         jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin đơn hàng"));

//         jLabel3.setText("Tên NV: ");

//         jLabel4.setText("Mã HD:");

//         jLabel5.setText("Giảm Giá");

//         jLabel13.setText("Ngày Tạo: ");

//         jLabel14.setText("Tổng Tiền: ");

//         jLabel15.setText("HT thanh toán:");

//         jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

//         jLabel17.setText("Tiền Khách Đưa:");

//         jTextField11.setEditable(false);

//         jLabel18.setText("Tiền khách CK:");

//         jTextField12.setEditable(false);
//         jTextField12.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField12ActionPerformed(evt);
//             }
//         });

//         jLabel19.setText("Tiền Trả Lại: ");

//         jTextField13.setEditable(false);
//         jTextField13.setEnabled(false);
//         jTextField13.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField13ActionPerformed(evt);
//             }
//         });

//         jTextField5.setEditable(false);
//         jTextField5.setBorder(null);
//         jTextField5.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField5ActionPerformed(evt);
//             }
//         });

//         jTextField6.setEditable(false);
//         jTextField6.setBorder(null);
//         jTextField6.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField6ActionPerformed(evt);
//             }
//         });

//         jTextField7.setEditable(false);
//         jTextField7.setBorder(null);
//         jTextField7.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField7ActionPerformed(evt);
//             }
//         });

//         jTextField8.setEditable(false);
//         jTextField8.setBorder(null);
//         jTextField8.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField8ActionPerformed(evt);
//             }
//         });

//         jTextField9.setEditable(false);
//         jTextField9.setBorder(null);
//         jTextField9.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField9ActionPerformed(evt);
//             }
//         });

//         jButton6.setBackground(new java.awt.Color(255, 153, 102));
//         jButton6.setForeground(new java.awt.Color(255, 0, 51));
//         jButton6.setText("làm Mới");

//         jButton7.setBackground(new java.awt.Color(255, 153, 102));
//         jButton7.setForeground(new java.awt.Color(255, 0, 0));
//         jButton7.setText("Thanh toán");

//         javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
//         jPanel7.setLayout(jPanel7Layout);
//         jPanel7Layout.setHorizontalGroup(
//             jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel7Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
//                         .addGap(13, 13, 13)
//                         .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                         .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
//                     .addGroup(jPanel7Layout.createSequentialGroup()
//                         .addComponent(jLabel17)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                         .addComponent(jTextField11))
//                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
//                         .addComponent(jLabel14)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                         .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
//                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
//                         .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addComponent(jLabel4)
//                             .addComponent(jLabel5)
//                             .addComponent(jLabel3)
//                             .addComponent(jLabel13))
//                         .addGap(37, 37, 37)
//                         .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                             .addComponent(jTextField8)
//                             .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
//                             .addComponent(jTextField6)
//                             .addComponent(jTextField7)))
//                     .addGroup(jPanel7Layout.createSequentialGroup()
//                         .addComponent(jLabel15)
//                         .addGap(18, 18, 18)
//                         .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
//                     .addGroup(jPanel7Layout.createSequentialGroup()
//                         .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addComponent(jLabel18)
//                             .addComponent(jLabel19))
//                         .addGap(18, 18, 18)
//                         .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addComponent(jTextField13)
//                             .addComponent(jTextField12))))
//                 .addContainerGap(27, Short.MAX_VALUE))
//         );
//         jPanel7Layout.setVerticalGroup(
//             jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel7Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jLabel4)
//                     .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jLabel3)
//                     .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jLabel5)
//                     .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jLabel13)
//                     .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jLabel14)
//                     .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addComponent(jLabel15)
//                     .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addGap(18, 18, 18)
//                 .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addComponent(jLabel17)
//                     .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jLabel18)
//                     .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
//                 .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addContainerGap())
//         );

//         javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//         jPanel1.setLayout(jPanel1Layout);
//         jPanel1Layout.setHorizontalGroup(
//             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//             .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//         );
//         jPanel1Layout.setVerticalGroup(
//             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel1Layout.createSequentialGroup()
//                 .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addGap(18, 18, 18)
//                 .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                 .addContainerGap())
//         );

//         jButton2.setBackground(new java.awt.Color(255, 153, 102));
//         jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/qr-code.png"))); // NOI18N
//         jButton2.setText("Quét mã");

//         jButton4.setBackground(new java.awt.Color(255, 153, 102));
//         jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/them.png"))); // NOI18N
//         jButton4.setText("Thêm hóa đơn");

//         javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
//         jPanel4.setLayout(jPanel4Layout);
//         jPanel4Layout.setHorizontalGroup(
//             jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel4Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addGroup(jPanel4Layout.createSequentialGroup()
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                             .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                         .addGap(12, 12, 12))
//                     .addGroup(jPanel4Layout.createSequentialGroup()
//                         .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
//                 .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addContainerGap())
//         );
//         jPanel4Layout.setVerticalGroup(
//             jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel4Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addGroup(jPanel4Layout.createSequentialGroup()
//                         .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                     .addGroup(jPanel4Layout.createSequentialGroup()
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addGroup(jPanel4Layout.createSequentialGroup()
//                                 .addGap(8, 8, 8)
//                                 .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                 .addGap(18, 18, 18)
//                                 .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
//                             .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                         .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                         .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addGap(14, 14, 14))))
//         );

//         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
//         this.setLayout(layout);
//         layout.setHorizontalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//         );
//         layout.setVerticalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//         );
//     }// </editor-fold>//GEN-END:initComponents

//     private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField12ActionPerformed

//     private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField13ActionPerformed

//     private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField5ActionPerformed

//     private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField6ActionPerformed

//     private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField7ActionPerformed

//     private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField8ActionPerformed

//     private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField9ActionPerformed


//     // Variables declaration - do not modify//GEN-BEGIN:variables
//     private javax.swing.JButton jButton2;
//     private javax.swing.JButton jButton4;
//     private javax.swing.JButton jButton5;
//     private javax.swing.JButton jButton6;
//     private javax.swing.JButton jButton7;
//     private javax.swing.JButton jButton9;
//     private javax.swing.JComboBox<String> jComboBox2;
//     private javax.swing.JLabel jLabel1;
//     private javax.swing.JLabel jLabel13;
//     private javax.swing.JLabel jLabel14;
//     private javax.swing.JLabel jLabel15;
//     private javax.swing.JLabel jLabel17;
//     private javax.swing.JLabel jLabel18;
//     private javax.swing.JLabel jLabel19;
//     private javax.swing.JLabel jLabel2;
//     private javax.swing.JLabel jLabel3;
//     private javax.swing.JLabel jLabel4;
//     private javax.swing.JLabel jLabel5;
//     private javax.swing.JPanel jPanel1;
//     private javax.swing.JPanel jPanel2;
//     private javax.swing.JPanel jPanel3;
//     private javax.swing.JPanel jPanel4;
//     private javax.swing.JPanel jPanel5;
//     private javax.swing.JPanel jPanel6;
//     private javax.swing.JPanel jPanel7;
//     private javax.swing.JScrollPane jScrollPane1;
//     private javax.swing.JScrollPane jScrollPane2;
//     private javax.swing.JScrollPane jScrollPane3;
//     private javax.swing.JTable jTable1;
//     private javax.swing.JTable jTable2;
//     private javax.swing.JTable jTable3;
//     private javax.swing.JTextField jTextField1;
//     private javax.swing.JTextField jTextField11;
//     private javax.swing.JTextField jTextField12;
//     private javax.swing.JTextField jTextField13;
//     private javax.swing.JTextField jTextField15;
//     private javax.swing.JTextField jTextField2;
//     private javax.swing.JTextField jTextField5;
//     private javax.swing.JTextField jTextField6;
//     private javax.swing.JTextField jTextField7;
//     private javax.swing.JTextField jTextField8;
//     private javax.swing.JTextField jTextField9;
//     // End of variables declaration//GEN-END:variables
// }
