// /*
//  * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
//  * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
//  */
// package DellStore.ui.manager;

// import DellStore.dao.impl.HoaDonDAO;
// import DellStore.dao.impl.ChiTietHoaDonDAO;
// import DellStore.entity.ChiTietHoaDonDTO;
// import DellStore.entity.HoaDonDTO;
// import DellStore.entity.hoadon;
// import DellStore.utils.XJdbc;
// import java.sql.Connection;
// import java.sql.DriverManager;
// import java.sql.PreparedStatement;
// import java.sql.ResultSet;
// import java.util.List;
// import javax.swing.JOptionPane;
// import javax.swing.table.DefaultTableModel;

// /**
//  *
//  * @author docon
//  */
// public class hoadonJPanel extends javax.swing.JPanel {

//     /**
//      * Creates new form hoadonJPanel
//      */
//     public hoadonJPanel() {
//         initComponents();
//         loadHoaDonTable();
//     }
//     private int getIdHoaDonByMa(String maHoaDon) {
//     String sql = "SELECT id FROM hoa_don WHERE ma = ?";
//     try (ResultSet rs = DellStore.utils.XJdbc.executeQuery(sql, maHoaDon)) {
//         if (rs.next()) return rs.getInt("id");
//     } catch (Exception e) {
//         e.printStackTrace();
//     }
//     return -1;
// }
    
// private void loadHoaDonTable() {
//     DefaultTableModel model = (DefaultTableModel) tbl_dshoadon.getModel();
//     model.setRowCount(0); // Xoá dữ liệu cũ

//     HoaDonDAO dao = new HoaDonDAO();
//     List<HoaDonDTO> list = dao.findAllDTO();

//     for (HoaDonDTO hd : list) {
//         model.addRow(new Object[]{
//             hd.getMa_hoa_don(),
//             hd.getNgay_tao(),
//             hd.getTen_nhan_vien(),
//             hd.getTrang_thai() == 1 ? "Đã thanh toán" : "Chưa thanh toán"
//         });
//     }
// }
// private void loadTableHoaDonChiTiet(int hoaDonId) {
//     DefaultTableModel model = (DefaultTableModel) tbl_hoadonchitiet.getModel();
//     model.setRowCount(0);
//     String sql = "SELECT * FROM vw_ct_hoa_don_display WHERE hoa_don_id = ?";
//     try (ResultSet rs = DellStore.utils.XJdbc.executeQuery(sql, hoaDonId)) {
//         int stt = 1;
//         while (rs.next()) {
//             model.addRow(new Object[]{
//                 stt++,
//                 rs.getString("hoa_don_id"),
//                 rs.getString("ten_san_pham"),
//                 rs.getBigDecimal("don_gia"),
//                 rs.getString("ma_serial"),
//                 rs.getInt("so_luong"),
//                 rs.getBigDecimal("tien_khuyen_mai"),
//                 rs.getBigDecimal("tong_tien")
//             });
//         }
//     } catch (Exception e) {
//         e.printStackTrace();
//         javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi tải chi tiết hóa đơn: " + e.getMessage());
//     }
// }
//     /**
//      * This method is called from within the constructor to initialize the form.
//      * WARNING: Do NOT modify this code. The content of this method is always
//      * regenerated by the Form Editor.
//      */
//     @SuppressWarnings("unchecked")
//     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//     private void initComponents() {

//         jPanel1 = new javax.swing.JPanel();
//         jPanel2 = new javax.swing.JPanel();
//         jScrollPane3 = new javax.swing.JScrollPane();
//         tbl_dshoadon = new javax.swing.JTable();
//         rdo_tatca = new javax.swing.JRadioButton();
//         rdo_chothanhtoan = new javax.swing.JRadioButton();
//         rdo_dathanhtoan = new javax.swing.JRadioButton();
//         rdo_huy = new javax.swing.JRadioButton();
//         txt_timkiem = new javax.swing.JTextField();
//         jButton4 = new javax.swing.JButton();
//         btn_export = new javax.swing.JButton();
//         btn_huyhoadon = new javax.swing.JButton();
//         jPanel3 = new javax.swing.JPanel();
//         jScrollPane2 = new javax.swing.JScrollPane();
//         tbl_hoadonchitiet = new javax.swing.JTable();
//         jPanel4 = new javax.swing.JPanel();
//         jLabel4 = new javax.swing.JLabel();
//         jLabel3 = new javax.swing.JLabel();
//         jLabel5 = new javax.swing.JLabel();
//         jLabel13 = new javax.swing.JLabel();
//         jLabel14 = new javax.swing.JLabel();
//         jLabel6 = new javax.swing.JLabel();
//         jLabel7 = new javax.swing.JLabel();
//         jLabel8 = new javax.swing.JLabel();
//         txt_mahoadon = new javax.swing.JTextField();
//         txt_tennv = new javax.swing.JTextField();
//         txt_khachhang = new javax.swing.JTextField();
//         txt_ngaytao = new javax.swing.JTextField();
//         txt_hinhthuc = new javax.swing.JTextField();
//         jLabel15 = new javax.swing.JLabel();
//         txt_tongtien = new javax.swing.JTextField();
//         txt_tinhtrang = new javax.swing.JTextField();
//         txt_tienck = new javax.swing.JTextField();
//         txt_tienkhachdua = new javax.swing.JTextField();
//         btn_inhoadon = new javax.swing.JButton();

//         jPanel1.setBackground(new java.awt.Color(255, 255, 255));

//         jPanel2.setBackground(new java.awt.Color(255, 255, 255));
//         jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 15))); // NOI18N

//         tbl_dshoadon.setModel(new javax.swing.table.DefaultTableModel(
//             new Object [][] {
//                 {null, null, null, null},
//                 {null, null, null, null},
//                 {null, null, null, null},
//                 {null, null, null, null}
//             },
//             new String [] {
//                 "Mã Hóa Đơn", "Ngày Tạo", "Tên Nhân Viên", "Tình Trạng"
//             }
//         ));
//         tbl_dshoadon.setGridColor(new java.awt.Color(255, 255, 255));
//         tbl_dshoadon.setSelectionBackground(new java.awt.Color(255, 255, 255));
//         tbl_dshoadon.addMouseListener(new java.awt.event.MouseAdapter() {
//             public void mouseClicked(java.awt.event.MouseEvent evt) {
//                 tbl_dshoadonMouseClicked(evt);
//             }
//         });
//         jScrollPane3.setViewportView(tbl_dshoadon);

//         rdo_tatca.setText("Tất Cả");

//         rdo_chothanhtoan.setText("Chờ Thanh Toán");

//         rdo_dathanhtoan.setText("Đã Thanh Toán");
//         rdo_dathanhtoan.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 rdo_dathanhtoanActionPerformed(evt);
//             }
//         });

//         rdo_huy.setText("Hủy");

//         jButton4.setBackground(new java.awt.Color(255, 153, 102));
//         jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/timkiem.png"))); // NOI18N
//         jButton4.setText("tìm kiếm");

//         btn_export.setBackground(new java.awt.Color(255, 153, 102));
//         btn_export.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/excel.png"))); // NOI18N
//         btn_export.setText("Export Excel");

//         btn_huyhoadon.setBackground(new java.awt.Color(255, 153, 102));
//         btn_huyhoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/xoa.png"))); // NOI18N
//         btn_huyhoadon.setText("Hủy Hóa Đơn");

//         javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
//         jPanel2.setLayout(jPanel2Layout);
//         jPanel2Layout.setHorizontalGroup(
//             jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel2Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addComponent(jScrollPane3)
//                     .addGroup(jPanel2Layout.createSequentialGroup()
//                         .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addComponent(rdo_huy)
//                             .addGroup(jPanel2Layout.createSequentialGroup()
//                                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                     .addComponent(rdo_tatca)
//                                     .addComponent(rdo_chothanhtoan)
//                                     .addComponent(rdo_dathanhtoan))
//                                 .addGap(103, 103, 103)
//                                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                     .addGroup(jPanel2Layout.createSequentialGroup()
//                                         .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                         .addGap(18, 18, 18)
//                                         .addComponent(jButton4))
//                                     .addGroup(jPanel2Layout.createSequentialGroup()
//                                         .addComponent(btn_export)
//                                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                         .addComponent(btn_huyhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
//                         .addGap(0, 17, Short.MAX_VALUE)))
//                 .addContainerGap())
//         );
//         jPanel2Layout.setVerticalGroup(
//             jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(rdo_tatca)
//                     .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(rdo_chothanhtoan)
//                     .addComponent(btn_export, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(btn_huyhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                 .addComponent(rdo_dathanhtoan)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                 .addComponent(rdo_huy)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//         );

//         jPanel3.setBackground(new java.awt.Color(255, 255, 255));
//         jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa Đơn Chi Tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 15))); // NOI18N

//         tbl_hoadonchitiet.setModel(new javax.swing.table.DefaultTableModel(
//             new Object [][] {
//                 {null, null, null, null, null, null, null, null},
//                 {null, null, null, null, null, null, null, null},
//                 {null, null, null, null, null, null, null, null},
//                 {null, null, null, null, null, null, null, null}
//             },
//             new String [] {
//                 "STT", "Mã HD", "Tên SP", "Giá ", "Serial", "Số Lượng", "Tiền KM", "Tổng Tiền"
//             }
//         ));
//         tbl_hoadonchitiet.setSelectionBackground(new java.awt.Color(255, 255, 255));
//         jScrollPane2.setViewportView(tbl_hoadonchitiet);

//         javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
//         jPanel3.setLayout(jPanel3Layout);
//         jPanel3Layout.setHorizontalGroup(
//             jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel3Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
//                 .addContainerGap())
//         );
//         jPanel3Layout.setVerticalGroup(
//             jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel3Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//         );

//         jPanel4.setBackground(new java.awt.Color(255, 255, 255));
//         jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 15))); // NOI18N

//         jLabel4.setText("Mã HD: ");

//         jLabel3.setText("Tên NV: ");

//         jLabel5.setText("Tên KH: ");

//         jLabel13.setText("Ngày Tạo");

//         jLabel14.setText("Hình Thức: ");

//         jLabel6.setText("Tình Trạng:");

//         jLabel7.setText("Tiền CK");

//         jLabel8.setText("Khách Đưa");

//         txt_mahoadon.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
//         txt_mahoadon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
//         txt_mahoadon.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 txt_mahoadonActionPerformed(evt);
//             }
//         });

//         txt_tennv.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
//         txt_tennv.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
//         txt_tennv.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 txt_tennvActionPerformed(evt);
//             }
//         });

//         txt_khachhang.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
//         txt_khachhang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
//         txt_khachhang.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 txt_khachhangActionPerformed(evt);
//             }
//         });

//         txt_ngaytao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
//         txt_ngaytao.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
//         txt_ngaytao.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 txt_ngaytaoActionPerformed(evt);
//             }
//         });

//         txt_hinhthuc.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
//         txt_hinhthuc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
//         txt_hinhthuc.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 txt_hinhthucActionPerformed(evt);
//             }
//         });

//         jLabel15.setText("Tổng Tiền:");

//         txt_tongtien.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
//         txt_tongtien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
//         txt_tongtien.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 txt_tongtienActionPerformed(evt);
//             }
//         });

//         txt_tinhtrang.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
//         txt_tinhtrang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
//         txt_tinhtrang.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 txt_tinhtrangActionPerformed(evt);
//             }
//         });

//         txt_tienck.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
//         txt_tienck.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
//         txt_tienck.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 txt_tienckActionPerformed(evt);
//             }
//         });

//         txt_tienkhachdua.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
//         txt_tienkhachdua.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
//         txt_tienkhachdua.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 txt_tienkhachduaActionPerformed(evt);
//             }
//         });

//         btn_inhoadon.setBackground(new java.awt.Color(255, 153, 102));
//         btn_inhoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/xuatdanhsach.png"))); // NOI18N
//         btn_inhoadon.setText("In Hóa Đơn");

//         javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
//         jPanel4.setLayout(jPanel4Layout);
//         jPanel4Layout.setHorizontalGroup(
//             jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel4Layout.createSequentialGroup()
//                 .addGap(85, 85, 85)
//                 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addGroup(jPanel4Layout.createSequentialGroup()
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                             .addComponent(jLabel14)
//                             .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                             .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                             .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                             .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addGap(22, 22, 22)
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addGroup(jPanel4Layout.createSequentialGroup()
//                                 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                     .addComponent(txt_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                     .addComponent(txt_khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                     .addComponent(txt_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                             .addGroup(jPanel4Layout.createSequentialGroup()
//                                 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                     .addComponent(txt_ngaytao, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                     .addComponent(txt_hinhthuc, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                 .addComponent(btn_inhoadon)
//                                 .addGap(259, 259, 259))))
//                     .addGroup(jPanel4Layout.createSequentialGroup()
//                         .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addGap(22, 22, 22)
//                         .addComponent(txt_mahoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
//                                 .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                 .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                             .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
//                         .addGap(44, 44, 44)
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addComponent(txt_tinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(txt_tienck, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(txt_tienkhachdua, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addGap(242, 242, 242))))
//         );
//         jPanel4Layout.setVerticalGroup(
//             jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel4Layout.createSequentialGroup()
//                 .addGap(19, 19, 19)
//                 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(txt_mahoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(txt_tinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addGap(19, 19, 19)
//                 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addGroup(jPanel4Layout.createSequentialGroup()
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                             .addComponent(txt_tienck, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                         .addGap(18, 18, 18)
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                             .addComponent(txt_tienkhachdua, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addGap(45, 45, 45)
//                         .addComponent(btn_inhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addGap(252, 252, 252))
//                     .addGroup(jPanel4Layout.createSequentialGroup()
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                             .addComponent(txt_tennv, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addGap(18, 18, 18)
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                             .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(txt_khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addGap(18, 18, 18)
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                             .addComponent(txt_ngaytao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addGap(18, 18, 18)
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                             .addComponent(txt_hinhthuc)
//                             .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addGap(18, 18, 18)
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                             .addComponent(txt_tongtien)
//                             .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
//         );

//         javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//         jPanel1.setLayout(jPanel1Layout);
//         jPanel1Layout.setHorizontalGroup(
//             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel1Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                     .addGroup(jPanel1Layout.createSequentialGroup()
//                         .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addGap(18, 18, 18)
//                         .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addGap(0, 50, Short.MAX_VALUE)))
//                 .addContainerGap())
//         );
//         jPanel1Layout.setVerticalGroup(
//             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel1Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                     .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                     .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                 .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addGap(160, 160, 160))
//         );

//         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
//         this.setLayout(layout);
//         layout.setHorizontalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//         );
//         layout.setVerticalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(layout.createSequentialGroup()
//                 .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addGap(0, 0, Short.MAX_VALUE))
//         );
//     }// </editor-fold>//GEN-END:initComponents


//     private void rdo_dathanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_dathanhtoanActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_rdo_dathanhtoanActionPerformed

//     private void txt_mahoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mahoadonActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_txt_mahoadonActionPerformed

//     private void txt_tennvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tennvActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_txt_tennvActionPerformed

//     private void txt_khachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_khachhangActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_txt_khachhangActionPerformed

//     private void txt_ngaytaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ngaytaoActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_txt_ngaytaoActionPerformed

//     private void txt_hinhthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hinhthucActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_txt_hinhthucActionPerformed

//     private void txt_tongtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tongtienActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_txt_tongtienActionPerformed

//     private void txt_tinhtrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tinhtrangActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_txt_tinhtrangActionPerformed

//     private void txt_tienckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tienckActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_txt_tienckActionPerformed

//     private void txt_tienkhachduaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tienkhachduaActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_txt_tienkhachduaActionPerformed

//     private void tbl_dshoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dshoadonMouseClicked
//    int selectedRow = tbl_dshoadon.getSelectedRow();
//     if (selectedRow != -1) {
//         String maHoaDon = tbl_dshoadon.getValueAt(selectedRow, 0).toString();
//         int hoaDonId = getIdHoaDonByMa(maHoaDon);
//         if (hoaDonId != -1) {
//             loadTableHoaDonChiTiet(hoaDonId);
//         }
//     }
//     }//GEN-LAST:event_tbl_dshoadonMouseClicked

// // Method để load thông tin chi tiết hóa đơn (khách hàng, tổng tiền, etc.)
// private void loadChiTietHoaDon(String maHoaDon) {
//     try {
//         System.out.println("Loading chi tiết hóa đơn cho mã: " + maHoaDon);
        
//         ChiTietHoaDonDAO dao = new ChiTietHoaDonDAO();
//         List<ChiTietHoaDonDTO> ds = dao.findByMaHoaDon(maHoaDon);
        
//         System.out.println("Số lượng chi tiết tìm được: " + ds.size());
        
//         DefaultTableModel model = (DefaultTableModel) tbl_hoadonchitiet.getModel();
//         model.setRowCount(0); // Xóa dữ liệu cũ
        
//         int stt = 1;
//         for (ChiTietHoaDonDTO dto : ds) {
//             System.out.println("Adding row " + stt + ": " + dto.toString());
            
//             model.addRow(new Object[]{
//                 stt++,                          // STT
//                 dto.getMaHoaDon(),              // Mã HD
//                 dto.getTenSanPham(),            // Tên SP
//                 dto.getDonGia(),                // Giá
//                 dto.getMaSerial(),              // Serial
//                 dto.getSoLuong(),               // Số Lượng
//                 dto.getTienKhuyenMai(),         // Tiền KM
//                 dto.getTongTien()               // Tổng Tiền
//             });
//         }
        
//         // Refresh table
//         tbl_hoadonchitiet.revalidate();
//         tbl_hoadonchitiet.repaint();
        
//         System.out.println("Hoàn thành load chi tiết hóa đơn");
        
//     } catch (Exception e) {
//         System.err.println("Lỗi chi tiết: " + e.getMessage());
//         e.printStackTrace();
//         javax.swing.JOptionPane.showMessageDialog(this, 
//             "Lỗi khi tải chi tiết hóa đơn: " + e.getMessage(), 
//             "Lỗi", 
//             javax.swing.JOptionPane.ERROR_MESSAGE);
//     }
// }

// // Method để tính tổng tiền khuyến mãi
// private void calculateTongTienKhuyenMai(String maHoaDon) {
//     try {
//         ChiTietHoaDonDAO dao = new ChiTietHoaDonDAO();
//         List<ChiTietHoaDonDTO> ds = dao.findByMaHoaDon(maHoaDon);
        
//         double tongTienKM = 0;
//         for (ChiTietHoaDonDTO dto : ds) {
//             if (dto.getTienKhuyenMai() != null) {
//                 tongTienKM += dto.getTienKhuyenMai().doubleValue();
//             }
//         }
        
//         txt_tienck.setText(String.valueOf(tongTienKM));
//     } catch (Exception e) {
//         e.printStackTrace();
//     }
// }

// // Method để clear form khi không có lựa chọn
// private void clearForm() {
//     txt_mahoadon.setText("");
//     txt_tennv.setText("");
//     txt_khachhang.setText("");
//     txt_ngaytao.setText("");
//     txt_hinhthuc.setText("");
//     txt_tongtien.setText("");
//     txt_tinhtrang.setText("");
//     txt_tienck.setText("");
//     txt_tienkhachdua.setText("");
    
//     // Clear bảng chi tiết
//     DefaultTableModel model = (DefaultTableModel) tbl_hoadonchitiet.getModel();
//     model.setRowCount(0);
// }

// // Nếu bạn muốn thêm method để lấy tên khách hàng từ ID
// // Bạn sẽ cần tạo DAO cho KhachHang
// /*
// private String getKhachHangById(int khachHangId) {
//     try {
//         // Giả sử bạn có KhachHangDAO
//         // KhachHangDAO khDao = new KhachHangDAO();
//         // KhachHang kh = khDao.findById(khachHangId);
//         // return kh != null ? kh.getTen() : "Khách lẻ";
//         return "Khách lẻ"; // Tạm thời
//     } catch (Exception e) {
//         return "Khách lẻ";
//     }
// }*/

//     // Variables declaration - do not modify//GEN-BEGIN:variables
//     private javax.swing.JButton btn_export;
//     private javax.swing.JButton btn_huyhoadon;
//     private javax.swing.JButton btn_inhoadon;
//     private javax.swing.JButton jButton4;
//     private javax.swing.JLabel jLabel13;
//     private javax.swing.JLabel jLabel14;
//     private javax.swing.JLabel jLabel15;
//     private javax.swing.JLabel jLabel3;
//     private javax.swing.JLabel jLabel4;
//     private javax.swing.JLabel jLabel5;
//     private javax.swing.JLabel jLabel6;
//     private javax.swing.JLabel jLabel7;
//     private javax.swing.JLabel jLabel8;
//     private javax.swing.JPanel jPanel1;
//     private javax.swing.JPanel jPanel2;
//     private javax.swing.JPanel jPanel3;
//     private javax.swing.JPanel jPanel4;
//     private javax.swing.JScrollPane jScrollPane2;
//     private javax.swing.JScrollPane jScrollPane3;
//     private javax.swing.JRadioButton rdo_chothanhtoan;
//     private javax.swing.JRadioButton rdo_dathanhtoan;
//     private javax.swing.JRadioButton rdo_huy;
//     private javax.swing.JRadioButton rdo_tatca;
//     private javax.swing.JTable tbl_dshoadon;
//     private javax.swing.JTable tbl_hoadonchitiet;
//     private javax.swing.JTextField txt_hinhthuc;
//     private javax.swing.JTextField txt_khachhang;
//     private javax.swing.JTextField txt_mahoadon;
//     private javax.swing.JTextField txt_ngaytao;
//     private javax.swing.JTextField txt_tennv;
//     private javax.swing.JTextField txt_tienck;
//     private javax.swing.JTextField txt_tienkhachdua;
//     private javax.swing.JTextField txt_timkiem;
//     private javax.swing.JTextField txt_tinhtrang;
//     private javax.swing.JTextField txt_tongtien;
//     // End of variables declaration//GEN-END:variables
// }
