// /*
//  * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
//  * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
//  */
// package DellStore.ui.manager;

// import DellStore.dao.impl.KhachHangDAOImpl;
// import DellStore.entity.khachhang;
// import java.text.SimpleDateFormat;
// import java.util.List;
// import javax.swing.JOptionPane;
// import javax.swing.table.DefaultTableModel;

// /**
//  *
//  * @author docon
//  */
// public class KhachHangJPanel extends javax.swing.JPanel {

//     /**
//      * Creates new form KhachHangJPanel
//      */
//     public KhachHangJPanel() {
//         initComponents();
//         fillTable();
//     }



// public void fillTable() {
//      DefaultTableModel model;
//        KhachHangDAOImpl dao = new KhachHangDAOImpl(); // DAO của bạn
//     model = (DefaultTableModel) tbl_khachhang.getModel();
//     model.setRowCount(0); // clear dữ liệu cũ

//     try {
//         List<khachhang> list = dao.findAll();
//         for (khachhang kh : list) {
//             model.addRow(new Object[] {
//                 kh.getId(),
//                 kh.getTen(),
//                 kh.getNgay_sinh(),
//                 kh.getGioi_tinh(),
//                 kh.getSdt(),
//                 kh.getEmail(),
//                 kh.getTrang_thai() == 1 ? "Đang hoạt động" : "Ngừng hoạt động"
//             });
//         }
//     } catch (Exception e) {
//         e.printStackTrace();
//         JOptionPane.showMessageDialog(null, "Lỗi khi tải danh sách khách hàng!");
//     }
// }


//     /**
//      * This method is called from within the constructor to initialize the form.
//      * WARNING: Do NOT modify this code. The content of this method is always
//      * regenerated by the Form Editor.
//      */
//     @SuppressWarnings("unchecked")
//     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//     private void initComponents() {

//         jPanel1 = new javax.swing.JPanel();
//         jPanel2 = new javax.swing.JPanel();
//         jLabel4 = new javax.swing.JLabel();
//         jLabel6 = new javax.swing.JLabel();
//         jLabel7 = new javax.swing.JLabel();
//         btnThem = new javax.swing.JButton();
//         btnSua = new javax.swing.JButton();
//         jTextField3 = new javax.swing.JTextField();
//         jTextField4 = new javax.swing.JTextField();
//         jTextField5 = new javax.swing.JTextField();
//         jLabel2 = new javax.swing.JLabel();
//         jTextField6 = new javax.swing.JTextField();
//         jLabel1 = new javax.swing.JLabel();
//         jPanel3 = new javax.swing.JPanel();
//         jTextField15 = new javax.swing.JTextField();
//         jButton5 = new javax.swing.JButton();
//         jLabel3 = new javax.swing.JLabel();
//         jScrollPane1 = new javax.swing.JScrollPane();
//         tbl_khachhang = new javax.swing.JTable();
//         jPanel4 = new javax.swing.JPanel();
//         jScrollPane2 = new javax.swing.JScrollPane();
//         jTable2 = new javax.swing.JTable();
//         jLabel11 = new javax.swing.JLabel();

//         jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

//         jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

//         jLabel4.setText("Tên khách hàng");

//         jLabel6.setText("Số Điện Thoại");

//         jLabel7.setText("Email");

//         btnThem.setBackground(new java.awt.Color(255, 153, 51));
//         btnThem.setText("Thêm");

//         btnSua.setBackground(new java.awt.Color(255, 153, 51));
//         btnSua.setText("Sửa");

//         jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
//         jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
//         jTextField3.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField3ActionPerformed(evt);
//             }
//         });

//         jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
//         jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
//         jTextField4.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField4ActionPerformed(evt);
//             }
//         });

//         jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
//         jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
//         jTextField5.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField5ActionPerformed(evt);
//             }
//         });

//         jLabel2.setText("Địa Chỉ");

//         jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
//         jTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
//         jTextField6.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField6ActionPerformed(evt);
//             }
//         });

//         javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
//         jPanel2.setLayout(jPanel2Layout);
//         jPanel2Layout.setHorizontalGroup(
//             jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel2Layout.createSequentialGroup()
//                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addGroup(jPanel2Layout.createSequentialGroup()
//                         .addGap(139, 139, 139)
//                         .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addGap(40, 40, 40)
//                         .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
//                     .addGroup(jPanel2Layout.createSequentialGroup()
//                         .addGap(54, 54, 54)
//                         .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addGroup(jPanel2Layout.createSequentialGroup()
//                                 .addGap(3, 3, 3)
//                                 .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
//                             .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                         .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
//                             .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
//                             .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
//                             .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
//                             .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
//                 .addContainerGap(85, Short.MAX_VALUE))
//         );
//         jPanel2Layout.setVerticalGroup(
//             jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel2Layout.createSequentialGroup()
//                 .addGap(21, 21, 21)
//                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addGap(10, 10, 10)
//                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addGap(23, 23, 23)
//                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addContainerGap(47, Short.MAX_VALUE))
//         );

//         jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//         jLabel1.setText("Thông Tin Khách Hàng");

//         jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Khách Hàng"));

//         jButton5.setBackground(new java.awt.Color(255, 153, 102));
//         jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/timkiem.png"))); // NOI18N
//         jButton5.setText("Tìm kiếm");
//         jButton5.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jButton5ActionPerformed(evt);
//             }
//         });

//         jLabel3.setText("Tìm Kiếm SDT");

//         tbl_khachhang.setModel(new javax.swing.table.DefaultTableModel(
//             new Object [][] {
//                 {null, null, null, null, null, null, null},
//                 {null, null, null, null, null, null, null},
//                 {null, null, null, null, null, null, null},
//                 {null, null, null, null, null, null, null}
//             },
//             new String [] {
//                 "ID", "Họ Tên", "Ngày Sinh", "Giới tính", "Số DT", "Email", "Trạng Thái"
//             }
//         ));
//         jScrollPane1.setViewportView(tbl_khachhang);

//         javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
//         jPanel3.setLayout(jPanel3Layout);
//         jPanel3Layout.setHorizontalGroup(
//             jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel3Layout.createSequentialGroup()
//                 .addGap(5, 5, 5)
//                 .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                 .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                 .addComponent(jButton5)
//                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//             .addGroup(jPanel3Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addComponent(jScrollPane1)
//                 .addContainerGap())
//         );
//         jPanel3Layout.setVerticalGroup(
//             jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel3Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                     .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                         .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
//                     .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                 .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//         );

//         jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

//         jTable2.setModel(new javax.swing.table.DefaultTableModel(
//             new Object [][] {
//                 {null, null, null, null, null},
//                 {null, null, null, null, null},
//                 {null, null, null, null, null},
//                 {null, null, null, null, null}
//             },
//             new String [] {
//                 "Mã SP", "Tên SP", "Ngày Mua", "Số Lượng", "Đơn Giá"
//             }
//         ));
//         jScrollPane2.setViewportView(jTable2);

//         javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
//         jPanel4.setLayout(jPanel4Layout);
//         jPanel4Layout.setHorizontalGroup(
//             jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel4Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
//                 .addContainerGap())
//         );
//         jPanel4Layout.setVerticalGroup(
//             jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel4Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//         );

//         jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//         jLabel11.setText("Sản Phẩm Đã Mua");

//         javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//         jPanel1.setLayout(jPanel1Layout);
//         jPanel1Layout.setHorizontalGroup(
//             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel1Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
//                     .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                     .addGroup(jPanel1Layout.createSequentialGroup()
//                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addGap(19, 19, 19)
//                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
//                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//         );
//         jPanel1Layout.setVerticalGroup(
//             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel1Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                     .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                 .addContainerGap())
//         );

//         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
//         this.setLayout(layout);
//         layout.setHorizontalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                 .addContainerGap())
//         );
//         layout.setVerticalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(layout.createSequentialGroup()
//                 .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addGap(0, 0, Short.MAX_VALUE))
//         );
//     }// </editor-fold>//GEN-END:initComponents

//     private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField3ActionPerformed

//     private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField4ActionPerformed

//     private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField5ActionPerformed

//     private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField6ActionPerformed

//     private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jButton5ActionPerformed


//     // Variables declaration - do not modify//GEN-BEGIN:variables
//     private javax.swing.JButton btnSua;
//     private javax.swing.JButton btnThem;
//     private javax.swing.JButton jButton5;
//     private javax.swing.JLabel jLabel1;
//     private javax.swing.JLabel jLabel11;
//     private javax.swing.JLabel jLabel2;
//     private javax.swing.JLabel jLabel3;
//     private javax.swing.JLabel jLabel4;
//     private javax.swing.JLabel jLabel6;
//     private javax.swing.JLabel jLabel7;
//     private javax.swing.JPanel jPanel1;
//     private javax.swing.JPanel jPanel2;
//     private javax.swing.JPanel jPanel3;
//     private javax.swing.JPanel jPanel4;
//     private javax.swing.JScrollPane jScrollPane1;
//     private javax.swing.JScrollPane jScrollPane2;
//     private javax.swing.JTable jTable2;
//     private javax.swing.JTextField jTextField15;
//     private javax.swing.JTextField jTextField3;
//     private javax.swing.JTextField jTextField4;
//     private javax.swing.JTextField jTextField5;
//     private javax.swing.JTextField jTextField6;
//     private javax.swing.JTable tbl_khachhang;
//     // End of variables declaration//GEN-END:variables
// }
