// /*
//  * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
//  * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
//  */
// package DellStore.ui.manager;

// import DellStore.dao.impl.khuyenmaiDAOImpl;
// import DellStore.entity.khuyenmai;
// import java.text.SimpleDateFormat;
// import java.util.List;
// import javax.swing.JOptionPane;
// import javax.swing.table.DefaultTableModel;

// /**
//  *
//  * @author docon
//  */
// public class KhuyenMaiJPanel extends javax.swing.JPanel {
// private khuyenmaiDAOImpl khuyenMaiDAO = new khuyenmaiDAOImpl();
//     /**
//      * Creates new form KhuyenMaiJPanel
//      */
//     public KhuyenMaiJPanel() {
//         initComponents();
//         fillTableKhuyenMai();
//     }
//    private void fillTableKhuyenMai() {
//     DefaultTableModel model = (DefaultTableModel) tbl_khuyenmai.getModel();
//     model.setRowCount(0); // Xóa dữ liệu cũ trong bảng

//     try {
//         List<khuyenmai> list = khuyenMaiDAO.findAll(); // Lấy danh sách khuyến mãi
//         SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy"); // Định dạng ngày

//         for (khuyenmai km : list) {
//             // Xử lý cột Giá trị
//             String giaTri;
//             if (km.getLoai_km()== null) {
//                 giaTri = "N/A";
//             } else if (km.getLoai_km().equals("%")) {
//                 giaTri = String.format("%.0f%%", km.getGia_tri()); // Hiển thị % mà không có số thập phân
//             } else if (km.getLoai_km().equals("tiền mặt")) {
//                 giaTri = String.format("%,.0f VNĐ", km.getGia_tri()); // Hiển thị tiền mặt với định dạng số
//             } else {
//                 giaTri = String.format("%,.2f", km.getGia_tri()); // Trường hợp bất ngờ, hiển thị số thô
//             }

//             Object[] row = {
//                 km.getMa_km()!= null ? km.getMa_km() : "N/A",
//                 km.getTen_km()!= null ? km.getTen_km() : "N/A",
//                 km.getLoai_km()!= null ? km.getLoai_km() : "N/A",
//                 giaTri,
//                 km.getNgay_bat_dau()!= null ? dateFormat.format(km.getNgay_bat_dau()) : "N/A",
//                 km.getNgay_ket_thuc()!= null ? dateFormat.format(km.getNgay_ket_thuc()) : "N/A",
//                 km.getTrang_thai()== 1 ? "Còn hiệu lực" : "Hết hạn"
//             };
//             model.addRow(row);
//         }
//         System.out.println("Loaded " + list.size() + " khuyến mãi");
//     } catch (Exception e) {
//         e.printStackTrace();
//         JOptionPane.showMessageDialog(this, 
//             "Lỗi khi tải dữ liệu khuyến mãi: " + e.getMessage(), 
//             "Lỗi", 
//             JOptionPane.ERROR_MESSAGE);
//     }
// }

//     /**
//      * This method is called from within the constructor to initialize the form.
//      * WARNING: Do NOT modify this code. The content of this method is always
//      * regenerated by the Form Editor.
//      */
//     @SuppressWarnings("unchecked")
//     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//     private void initComponents() {

//         jLabel1 = new javax.swing.JLabel();
//         jPanel1 = new javax.swing.JPanel();
//         jLabel2 = new javax.swing.JLabel();
//         jLabel3 = new javax.swing.JLabel();
//         jLabel4 = new javax.swing.JLabel();
//         jLabel5 = new javax.swing.JLabel();
//         jLabel6 = new javax.swing.JLabel();
//         jLabel7 = new javax.swing.JLabel();
//         jSeparator1 = new javax.swing.JSeparator();
//         jSeparator2 = new javax.swing.JSeparator();
//         jComboBox1 = new javax.swing.JComboBox<>();
//         jComboBox2 = new javax.swing.JComboBox<>();
//         jTextField1 = new javax.swing.JTextField();
//         jButton1 = new javax.swing.JButton();
//         jTextField2 = new javax.swing.JTextField();
//         jButton2 = new javax.swing.JButton();
//         jButton3 = new javax.swing.JButton();
//         jButton4 = new javax.swing.JButton();
//         jPanel2 = new javax.swing.JPanel();
//         jLabel8 = new javax.swing.JLabel();
//         jLabel9 = new javax.swing.JLabel();
//         jScrollPane1 = new javax.swing.JScrollPane();
//         tbl_khuyenmai = new javax.swing.JTable();
//         rdo_conhieuluc = new javax.swing.JRadioButton();
//         rdo_hethieuluc = new javax.swing.JRadioButton();
//         txt_tensp = new javax.swing.JTextField();
//         txt_timkm = new javax.swing.JTextField();
//         jPanel3 = new javax.swing.JPanel();
//         jLabel10 = new javax.swing.JLabel();
//         jSeparator4 = new javax.swing.JSeparator();
//         jScrollPane2 = new javax.swing.JScrollPane();
//         tbl_sanpham = new javax.swing.JTable();
//         jButton5 = new javax.swing.JButton();

//         jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
//         jLabel1.setForeground(new java.awt.Color(255, 0, 51));
//         jLabel1.setText("Khuyến Mại");

//         jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
//         jLabel2.setText("Loại khuyến mại");

//         jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
//         jLabel3.setText("Tên khuyến mại");

//         jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
//         jLabel4.setText("Giá trị");

//         jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
//         jLabel5.setText("Ngày bắt đầu");

//         jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
//         jLabel6.setText("Ngày kết thúc");

//         jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
//         jLabel7.setText("Trạng thái");

//         jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

//         jButton1.setText("...");

//         jButton2.setText("...");

//         jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
//         jButton3.setText("Thêm");

//         jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
//         jButton4.setText("Cập nhật");

//         javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//         jPanel1.setLayout(jPanel1Layout);
//         jPanel1Layout.setHorizontalGroup(
//             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel1Layout.createSequentialGroup()
//                 .addGap(15, 15, 15)
//                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                         .addComponent(jLabel3)
//                         .addGap(18, 18, 18)
//                         .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
//                     .addGroup(jPanel1Layout.createSequentialGroup()
//                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                             .addComponent(jButton3)
//                             .addComponent(jLabel2))
//                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addGroup(jPanel1Layout.createSequentialGroup()
//                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                 .addComponent(jButton4)
//                                 .addGap(42, 42, 42))
//                             .addGroup(jPanel1Layout.createSequentialGroup()
//                                 .addGap(6, 6, 6)
//                                 .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                 .addGap(0, 0, Short.MAX_VALUE))))
//                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addComponent(jLabel4)
//                             .addComponent(jLabel5)
//                             .addComponent(jLabel6)
//                             .addComponent(jLabel7))
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                             .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                             .addGroup(jPanel1Layout.createSequentialGroup()
//                                 .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                 .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
//                             .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addGroup(jPanel1Layout.createSequentialGroup()
//                                 .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                 .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
//                 .addContainerGap(16, Short.MAX_VALUE))
//         );
//         jPanel1Layout.setVerticalGroup(
//             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel1Layout.createSequentialGroup()
//                 .addGap(21, 21, 21)
//                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                     .addComponent(jLabel3)
//                     .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addGap(33, 33, 33)
//                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jLabel2)
//                     .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addGap(35, 35, 35)
//                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                     .addComponent(jLabel4)
//                     .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addGap(30, 30, 30)
//                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jLabel5)
//                     .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jButton1))
//                 .addGap(30, 30, 30)
//                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jLabel6)
//                     .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jButton2))
//                 .addGap(29, 29, 29)
//                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jLabel7)
//                     .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addGap(68, 68, 68)
//                 .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jButton3)
//                     .addComponent(jButton4))
//                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//         );

//         jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
//         jLabel8.setText("Tìm khuyến mại");

//         jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
//         jLabel9.setText("Trạng thái");

//         tbl_khuyenmai.setModel(new javax.swing.table.DefaultTableModel(
//             new Object [][] {

//             },
//             new String [] {
//                 "Mã KM", "Tên KM", "Loại KM", "Giá trị", "Ngày bắt đầu", "Ngày kết thúc", "Trạng thái"
//             }
//         ) {
//             boolean[] canEdit = new boolean [] {
//                 false, false, false, false, false, false, false
//             };

//             public boolean isCellEditable(int rowIndex, int columnIndex) {
//                 return canEdit [columnIndex];
//             }
//         });
//         jScrollPane1.setViewportView(tbl_khuyenmai);

//         rdo_conhieuluc.setText("còn hiệu lực");

//         rdo_hethieuluc.setText("Hết hiệu lực");

//         txt_tensp.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
//         txt_tensp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
//         txt_tensp.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 txt_tenspActionPerformed(evt);
//             }
//         });

//         txt_timkm.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
//         txt_timkm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
//         txt_timkm.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 txt_timkmActionPerformed(evt);
//             }
//         });

//         javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
//         jPanel2.setLayout(jPanel2Layout);
//         jPanel2Layout.setHorizontalGroup(
//             jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel2Layout.createSequentialGroup()
//                 .addGap(20, 20, 20)
//                 .addComponent(jLabel8)
//                 .addGap(18, 18, 18)
//                 .addComponent(txt_timkm, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
//                 .addGap(233, 233, 233)
//                 .addComponent(jLabel9)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addComponent(rdo_conhieuluc)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                 .addComponent(rdo_hethieuluc)
//                 .addContainerGap(58, Short.MAX_VALUE))
//             .addGroup(jPanel2Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addComponent(jScrollPane1)
//                 .addContainerGap())
//             .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                 .addGroup(jPanel2Layout.createSequentialGroup()
//                     .addGap(344, 344, 344)
//                     .addComponent(txt_tensp, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
//                     .addGap(344, 344, 344)))
//         );
//         jPanel2Layout.setVerticalGroup(
//             jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel2Layout.createSequentialGroup()
//                 .addGap(17, 17, 17)
//                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                     .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                         .addComponent(jLabel9)
//                         .addComponent(rdo_conhieuluc)
//                         .addComponent(rdo_hethieuluc))
//                     .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                         .addComponent(jLabel8)
//                         .addComponent(txt_timkm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                 .addGap(18, 18, 18)
//                 .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addContainerGap(16, Short.MAX_VALUE))
//             .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                 .addGroup(jPanel2Layout.createSequentialGroup()
//                     .addGap(139, 139, 139)
//                     .addComponent(txt_tensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addContainerGap(140, Short.MAX_VALUE)))
//         );

//         jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
//         jLabel10.setText("Tìn sản phẩm");

//         tbl_sanpham.setModel(new javax.swing.table.DefaultTableModel(
//             new Object [][] {

//             },
//             new String [] {
//                 "Mã SP", "Tên SP", "CPU", "Hãng", "Ram", "Card", "Ổ cứng", "Giá"
//             }
//         ) {
//             boolean[] canEdit = new boolean [] {
//                 false, false, false, false, false, false, false, false
//             };

//             public boolean isCellEditable(int rowIndex, int columnIndex) {
//                 return canEdit [columnIndex];
//             }
//         });
//         jScrollPane2.setViewportView(tbl_sanpham);

//         javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
//         jPanel3.setLayout(jPanel3Layout);
//         jPanel3Layout.setHorizontalGroup(
//             jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel3Layout.createSequentialGroup()
//                 .addGap(24, 24, 24)
//                 .addComponent(jLabel10)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//             .addGroup(jPanel3Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addComponent(jScrollPane2)
//                 .addContainerGap())
//         );
//         jPanel3Layout.setVerticalGroup(
//             jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel3Layout.createSequentialGroup()
//                 .addGap(26, 26, 26)
//                 .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                     .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jLabel10))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                 .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addContainerGap(12, Short.MAX_VALUE))
//         );

//         jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
//         jButton5.setText("Áp dụng khuyến mại");

//         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
//         this.setLayout(layout);
//         layout.setHorizontalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(layout.createSequentialGroup()
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addGroup(layout.createSequentialGroup()
//                         .addGap(109, 109, 109)
//                         .addComponent(jLabel1))
//                     .addGroup(layout.createSequentialGroup()
//                         .addContainerGap()
//                         .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                 .addGap(32, 32, 32)
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                     .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                     .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                     .addGroup(layout.createSequentialGroup()
//                         .addGap(6, 6, 6)
//                         .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                 .addContainerGap(42, Short.MAX_VALUE))
//         );
//         layout.setVerticalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(layout.createSequentialGroup()
//                 .addGap(19, 19, 19)
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addGroup(layout.createSequentialGroup()
//                         .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addGap(27, 27, 27)
//                         .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                         .addComponent(jButton5)
//                         .addGap(0, 0, Short.MAX_VALUE))
//                     .addGroup(layout.createSequentialGroup()
//                         .addComponent(jLabel1)
//                         .addGap(38, 38, 38)
//                         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
//                 .addContainerGap())
//         );
//     }// </editor-fold>//GEN-END:initComponents

//     private void txt_tenspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenspActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_txt_tenspActionPerformed

//     private void txt_timkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timkmActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_txt_timkmActionPerformed


//     // Variables declaration - do not modify//GEN-BEGIN:variables
//     private javax.swing.JButton jButton1;
//     private javax.swing.JButton jButton2;
//     private javax.swing.JButton jButton3;
//     private javax.swing.JButton jButton4;
//     private javax.swing.JButton jButton5;
//     private javax.swing.JComboBox<String> jComboBox1;
//     private javax.swing.JComboBox<String> jComboBox2;
//     private javax.swing.JLabel jLabel1;
//     private javax.swing.JLabel jLabel10;
//     private javax.swing.JLabel jLabel2;
//     private javax.swing.JLabel jLabel3;
//     private javax.swing.JLabel jLabel4;
//     private javax.swing.JLabel jLabel5;
//     private javax.swing.JLabel jLabel6;
//     private javax.swing.JLabel jLabel7;
//     private javax.swing.JLabel jLabel8;
//     private javax.swing.JLabel jLabel9;
//     private javax.swing.JPanel jPanel1;
//     private javax.swing.JPanel jPanel2;
//     private javax.swing.JPanel jPanel3;
//     private javax.swing.JScrollPane jScrollPane1;
//     private javax.swing.JScrollPane jScrollPane2;
//     private javax.swing.JSeparator jSeparator1;
//     private javax.swing.JSeparator jSeparator2;
//     private javax.swing.JSeparator jSeparator4;
//     private javax.swing.JTextField jTextField1;
//     private javax.swing.JTextField jTextField2;
//     private javax.swing.JRadioButton rdo_conhieuluc;
//     private javax.swing.JRadioButton rdo_hethieuluc;
//     private javax.swing.JTable tbl_khuyenmai;
//     private javax.swing.JTable tbl_sanpham;
//     private javax.swing.JTextField txt_tensp;
//     private javax.swing.JTextField txt_timkm;
//     // End of variables declaration//GEN-END:variables
// }
