/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DellStore.ui.manager;

import DellStore.dao.impl.LoaiSanPhamDAO;
import DellStore.ui.JDialog.cardJDialog;
import DellStore.ui.JDialog.cpujDialog;
import DellStore.ui.JDialog.ramJDialog;
import DellStore.ui.JDialog.ocungJDialog;
import DellStore.dao.impl.cardDAOImpl;
import DellStore.dao.impl.chitietsanphamDAO;
import DellStore.dao.impl.cpuDAOImpl;
import DellStore.dao.impl.hangDAOImpl;
import DellStore.dao.impl.ocungDAOImpl;
import DellStore.dao.impl.ramDAOImpl;
import DellStore.dao.impl.sanphamDAO;
import DellStore.entity.SanPhamChiTietViewModel;
import DellStore.entity.card;
import DellStore.entity.chitietsanpham;
import DellStore.entity.cpu;
import DellStore.entity.hang;
import DellStore.entity.loadsanpham;
import DellStore.entity.nhanvien;
import DellStore.entity.ocung;
import DellStore.entity.ram;
import DellStore.entity.sanpham;
import DellStore.utils.XJdbc;
import DellStore.dao.impl.SerialDAOImpl;
import DellStore.entity.serial;
import DellStore.ui.JDialog.ChiTietSanPhamJDialog;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

import DellStore.entity.loadsanpham;
import java.util.ArrayList;
public class SanPhamJPanel extends javax.swing.JPanel {
    private sanphamDAO daosp = new sanphamDAO();
    private chitietsanphamDAO ctspDAO = new chitietsanphamDAO();
    private ocungDAOImpl oImpl = new ocungDAOImpl();
    private cardDAOImpl cImpl = new cardDAOImpl();
    private cpuDAOImpl cpImpl = new cpuDAOImpl();
    private ramDAOImpl rImpl = new ramDAOImpl();
    private SerialDAOImpl serialdao  = new SerialDAOImpl();
    private List<loadsanpham> listLoaiSP = new ArrayList<>();
    private LoaiSanPhamDAO loaiSPDAO = new LoaiSanPhamDAO();
    private LoaiSanPhamDAO loaiSanPhamDAO = new LoaiSanPhamDAO();
    private  hangDAOImpl hangDAO = new hangDAOImpl();

  
    
    public SanPhamJPanel() {
        initComponents();
      

        txt_timkiemsanpham.getDocument().addDocumentListener(new DocumentListener() {
    public void insertUpdate(DocumentEvent e) { timKiemTuDong(); }
    public void removeUpdate(DocumentEvent e) { timKiemTuDong(); }
    public void changedUpdate(DocumentEvent e) { timKiemTuDong(); }
    private void timKiemTuDong() {
        String keyword = txt_timkiemsanpham.getText().trim().toLowerCase();
        DefaultTableModel model = (DefaultTableModel) tbl_bangsanpham.getModel();
        model.setRowCount(0);
        List<sanpham> list = daosp.findAll();
        int stt = 1;
        for (sanpham entity : list) {
            if (keyword.isEmpty() || entity.getTen().toLowerCase().contains(keyword)) {
                model.addRow(new Object[]{
                    stt++,
                    entity.getTen(),
                    entity.getMasp(),
                    entity.getSo_luong()
                      
                });
            }
        }
    }
});
         DefaultTableModel model = new DefaultTableModel();
   model.setColumnIdentifiers(new Object[]{
   "id", "Tên sản phẩm", "CPU", "Card", "Hãng", "Ổ Cứng", "Ram", "Serial", "Giá bán", "Trạng thái"
});
    tbl_bangDSSanPham.setModel(model);
        fillComboBoxRam();
        fillComboBoxCPU();
        fillComboBoxHang();
        fillComboBoxhang1();
        fillComboBoxOCung();
        fillComboBoxGPU();
        fillLoaiSanPham();
        loadTableSanPham();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txt_timkiemsanpham = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_themsanpham = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_bangsanpham = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbo_hang = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cbo_loaisanpham = new javax.swing.JComboBox<>();
        txt_tensanpham = new javax.swing.JTextField();
        txt_masanpham = new javax.swing.JTextField();
        txt_mota = new javax.swing.JTextField();
        txt_soLuong = new javax.swing.JTextField();
        btn_quetqr = new javax.swing.JButton();
        btn_lammoi = new javax.swing.JButton();
        rdo_conban = new javax.swing.JRadioButton();
        rdo_ngungkinhdoanh = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_bangDSSanPham = new javax.swing.JTable();
        txt_timkiemdssanpham = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_Import = new javax.swing.JButton();
        btn_Export = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_tensp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_gia = new javax.swing.JTextField();
        btn_lammoidssanpham = new javax.swing.JButton();
        btn_suasanpham1 = new javax.swing.JButton();
        txt_serial = new javax.swing.JTextField();
        rdo_dangban = new javax.swing.JRadioButton();
        rdo_daban = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_idChiTiet = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbo_CPU = new javax.swing.JComboBox<>();
        btn_themHang = new javax.swing.JButton();
        cbo_Card = new javax.swing.JComboBox<>();
        btn_themRam = new javax.swing.JButton();
        cbo_Ram = new javax.swing.JComboBox<>();
        btn_ThemCard = new javax.swing.JButton();
        cbo_Hang = new javax.swing.JComboBox<>();
        btn_themCPU = new javax.swing.JButton();
        cbo_OCung = new javax.swing.JComboBox<>();
        btn_themOCung = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1120, 660));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("THÔNG TIN SẢN PHẨM"));

        txt_timkiemsanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timkiemsanphamActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Tìm kiếm:");

        btn_themsanpham.setBackground(new java.awt.Color(255, 153, 102));
        btn_themsanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/them.png"))); // NOI18N
        btn_themsanpham.setText("Thêm");
        btn_themsanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themsanphamActionPerformed(evt);
            }
        });

        tbl_bangsanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Tên Sản Phẩm", "Mã Sản Phẩm", "Số Lượng"
            }
        ));
        tbl_bangsanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bangsanphamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_bangsanpham);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mô Tả:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tên Sản Phẩm:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Mã Sản Phẩm:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Hãng:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Trạng Thái:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Số Lượng");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Loại Sản Phẩm:");

        btn_quetqr.setBackground(new java.awt.Color(255, 153, 102));
        btn_quetqr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/qr-code.png"))); // NOI18N
        btn_quetqr.setText("Quét QR");
        btn_quetqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quetqrActionPerformed(evt);
            }
        });

        btn_lammoi.setBackground(new java.awt.Color(255, 153, 102));
        btn_lammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/reset.png"))); // NOI18N
        btn_lammoi.setText("Làm Mới");
        btn_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoiActionPerformed(evt);
            }
        });

        rdo_conban.setText("Còn Bán");

        rdo_ngungkinhdoanh.setText("Ngừng Kinh Doanh");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbo_loaisanpham, 0, 197, Short.MAX_VALUE)
                                    .addComponent(txt_tensanpham)
                                    .addComponent(txt_masanpham)
                                    .addComponent(txt_mota))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbo_hang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_soLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdo_conban)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdo_ngungkinhdoanh)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(btn_themsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(btn_quetqr, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(179, 179, 179)
                                        .addComponent(btn_lammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(101, 101, 101))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txt_timkiemsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbo_hang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tensanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_masanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdo_conban)
                            .addComponent(rdo_ngungkinhdoanh))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_mota, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbo_loaisanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_timkiemsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_themsanpham)
                            .addComponent(btn_quetqr))
                        .addGap(18, 18, 18)
                        .addComponent(btn_lammoi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sản Phẩm", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "DANH SÁCH SẢN PHẨM"));

        tbl_bangDSSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên SP", "CPU", "Card", "Hãng", "Ổ Cứng", "Ram", "Serial", "Giá Bán", "Trạng Thái"
            }
        ));
        tbl_bangDSSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bangDSSanPhamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_bangDSSanPham);

        txt_timkiemdssanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timkiemdssanphamActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Tìm kiếm:");

        btn_Import.setBackground(new java.awt.Color(255, 153, 102));
        btn_Import.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/excel.png"))); // NOI18N
        btn_Import.setText("Import");

        btn_Export.setBackground(new java.awt.Color(255, 153, 102));
        btn_Export.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/excel.png"))); // NOI18N
        btn_Export.setText("Export");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txt_timkiemdssanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220)
                        .addComponent(btn_Import)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Export)))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_timkiemdssanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Import, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Export, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Chức Năng"));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Tên SP:");

        txt_tensp.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_tensp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_tensp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenspActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Serial:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Giá:");

        txt_gia.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_gia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_gia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_giaActionPerformed(evt);
            }
        });

        btn_lammoidssanpham.setBackground(new java.awt.Color(255, 153, 102));
        btn_lammoidssanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/reset.png"))); // NOI18N
        btn_lammoidssanpham.setText("Làm Mới");
        btn_lammoidssanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoidssanphamActionPerformed(evt);
            }
        });

        btn_suasanpham1.setBackground(new java.awt.Color(255, 153, 102));
        btn_suasanpham1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/them.png"))); // NOI18N
        btn_suasanpham1.setText("Sửa");
        btn_suasanpham1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suasanpham1ActionPerformed(evt);
            }
        });

        txt_serial.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_serial.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_serial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_serialActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdo_dangban);
        rdo_dangban.setText("Đang Bán");

        buttonGroup1.add(rdo_daban);
        rdo_daban.setText("Đã Bán");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setText("Trạng Thái:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel14.setText("STT");

        txt_idChiTiet.setEditable(false);
        txt_idChiTiet.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_idChiTiet.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_idChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idChiTietActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btn_lammoidssanpham)
                        .addGap(44, 44, 44)
                        .addComponent(btn_suasanpham1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(rdo_dangban)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdo_daban))
                            .addComponent(txt_tensp, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(txt_gia)
                            .addComponent(txt_serial, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(txt_idChiTiet))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_idChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_tensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_serial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdo_dangban)
                        .addComponent(jLabel13))
                    .addComponent(rdo_daban))
                .addGap(38, 38, 38)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_lammoidssanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_suasanpham1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thuộc Tính"));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Hãng: ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Ram: ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Card: ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("CPU: ");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Ổ Cứng: ");

        cbo_CPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_CPUActionPerformed(evt);
            }
        });

        btn_themHang.setBackground(new java.awt.Color(255, 153, 102));
        btn_themHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/them.png"))); // NOI18N
        btn_themHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themHangActionPerformed(evt);
            }
        });

        btn_themRam.setBackground(new java.awt.Color(255, 153, 102));
        btn_themRam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/them.png"))); // NOI18N
        btn_themRam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themRamActionPerformed(evt);
            }
        });

        btn_ThemCard.setBackground(new java.awt.Color(255, 153, 102));
        btn_ThemCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/them.png"))); // NOI18N
        btn_ThemCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemCardActionPerformed(evt);
            }
        });

        btn_themCPU.setBackground(new java.awt.Color(255, 153, 102));
        btn_themCPU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/them.png"))); // NOI18N
        btn_themCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themCPUActionPerformed(evt);
            }
        });

        cbo_OCung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_OCungActionPerformed(evt);
            }
        });

        btn_themOCung.setBackground(new java.awt.Color(255, 153, 102));
        btn_themOCung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/them.png"))); // NOI18N
        btn_themOCung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themOCungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(28, 28, 28)
                                .addComponent(cbo_CPU, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(btn_themCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(254, 254, 254)
                                .addComponent(btn_themOCung, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbo_Hang, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(112, 112, 112)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbo_Ram, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbo_OCung, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(111, 111, 111)
                                .addComponent(jLabel10)
                                .addGap(28, 28, 28)
                                .addComponent(cbo_Card, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btn_themHang, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(251, 251, 251)
                        .addComponent(btn_themRam, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ThemCard, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(cbo_Ram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cbo_Card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_Hang, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_themHang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_themRam, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ThemCard, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_CPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(cbo_OCung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_themCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_themOCung, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(74, 74, 74))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Chi Tiết Sản Phẩm", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

  private void fillComboBoxRam() {
    cbo_Ram.removeAllItems();
    List<ram> list = rImpl.getAllRAM();  
    for (ram o : list) {
        cbo_Ram.addItem(o); 
    }
}

private void fillComboBoxCPU() {
    cbo_CPU.removeAllItems();
    List<cpu> list = cpImpl.getAllCPU();  
    for (cpu o : list) {
        cbo_CPU.addItem(o); 
    }

    
}


public void fillComboBoxHang() {
    hangDAOImpl dao = new hangDAOImpl();
    List<hang> list = dao.findAll();
    cbo_Hang.removeAllItems();
    for (hang item : list) {
        cbo_Hang.addItem(item.getTen());
    }
}
public void fillComboBoxhang1() {
   DefaultComboBoxModel<hang> model = new DefaultComboBoxModel<>();
for (hang h : hangDAO.findAll()) {
    model.addElement(h);
}
cbo_hang.setModel(model);

}



public void fillComboBoxOCung() {
    cbo_OCung.removeAllItems();
    List<ocung> list = oImpl.getAllOCung();  
    for (ocung o : list) {
        cbo_OCung.addItem(o); 
    }

}

public void fillComboBoxGPU() {
     cbo_Card.removeAllItems();
    List<card> list = cImpl.getAllCard();  
    for (card o : list) {
        cbo_Card.addItem(o); 
    }

}

private void loadTableSanPham() {
    DefaultTableModel model = (DefaultTableModel) tbl_bangsanpham.getModel();
    model.setRowCount(0);
    List<sanpham> list = daosp.findAll();
    int stt = 1;
    for (sanpham sp : list) {
        model.addRow(new Object[]{stt++, sp.getTen(), sp.getMasp(),sp.getSo_luong()});
    }
}
private void fillLoaiSanPham() {
    cbo_loaisanpham.removeAllItems();
    List<loadsanpham> list = loaiSanPhamDAO.findAll();

    for (loadsanpham loai : list) {
        cbo_loaisanpham.addItem(loai);
    }
}



    
    private void txt_tenspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenspActionPerformed

    private void txt_giaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_giaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_giaActionPerformed

    private void btn_lammoidssanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoidssanphamActionPerformed

        txt_tensp.setText("");
        cbo_CPU.setSelectedIndex(-1);
        cbo_Card.setSelectedIndex(-1);
        cbo_Hang.setSelectedIndex(-1);
        cbo_OCung.setSelectedIndex(-1);
        cbo_Ram.setSelectedIndex(-1);
        txt_serial.setText("");
        txt_gia.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btn_lammoidssanphamActionPerformed
 private void fillFormFromTable() {
        int row = tbl_bangDSSanPham.getSelectedRow();
        if (row >= 0) {
            cbo_CPU.setSelectedItem(tbl_bangDSSanPham.getValueAt(row, 1).toString());
            cbo_Card.setSelectedItem(tbl_bangDSSanPham.getValueAt(row, 2).toString());
            cbo_OCung.setSelectedItem(tbl_bangDSSanPham.getValueAt(row, 4).toString());
            cbo_Ram.setSelectedItem(tbl_bangDSSanPham.getValueAt(row, 5).toString());
            txt_serial.setText(tbl_bangDSSanPham.getValueAt(row, 6).toString());
            txt_gia.setText(tbl_bangDSSanPham.getValueAt(row, 7).toString());
        }
    }
    private void btn_suasanpham1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suasanpham1ActionPerformed

}//GEN-LAST:event_btn_suasanpham1ActionPerformed
 private void loadDataToTable() {
    DefaultTableModel model = (DefaultTableModel) tbl_bangDSSanPham.getModel();
    model.setRowCount(0);
    
    List<chitietsanpham> list = ctspDAO.findAll();
    for (chitietsanpham ct : list) {
        Object[] row = new Object[] {
            ct.getId(),
            ctspDAO.getTenById("cpu", ct.getCpu_id()),
            ctspDAO.getTenById("gpu", ct.getGpu_id()),
            "Dell", // Hoặc: ctspDAO.getTenById("hang", ct.getHang_id()) nếu có
            ctspDAO.getTenById("ssd", ct.getSsd_id()),
            ctspDAO.getTenById("ram", ct.getRam_id()),
            ct.getSerial_id(), // Nếu cần tên serial, bạn có thể viết thêm getTenSerialById()
            ct.getGia_ban(),
            ct.getSo_luong_ton()
        };
        model.addRow(row);
    }
}


    private void cbo_CPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_CPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_CPUActionPerformed

    private void cbo_OCungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_OCungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_OCungActionPerformed

    private void txt_timkiemdssanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timkiemdssanphamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timkiemdssanphamActionPerformed

    private void btn_themCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themCPUActionPerformed
    JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
    cpujDialog dialog = new cpujDialog(parent, true);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
    }//GEN-LAST:event_btn_themCPUActionPerformed

    private void btn_themRamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themRamActionPerformed
        // TODO add your handling code here:
    JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
    ramJDialog dialog = new ramJDialog(parent, true);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
    }//GEN-LAST:event_btn_themRamActionPerformed

    private void btn_themOCungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themOCungActionPerformed
        // TODO add your handling code here:
    JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
    ocungJDialog dialog = new ocungJDialog(parent, true);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
    }//GEN-LAST:event_btn_themOCungActionPerformed

    private void btn_ThemCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemCardActionPerformed
        // TODO add your handling code here:
    JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
    cardJDialog dialog = new cardJDialog(parent, true);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
    }//GEN-LAST:event_btn_ThemCardActionPerformed

//    private void tbl_bangDSSanPhamMouseClicked(java.awt.event.MouseEvent evt) {                                               
//  

//}

public int getIdLoaiSP(String ten) {
    for (loadsanpham lsp : listLoaiSP) {
        if (lsp.getTen().equalsIgnoreCase(ten)) {
            return lsp.getId();
        }
    }
    return -1;
}

    private void txt_serialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_serialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_serialActionPerformed

    private void txt_timkiemsanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timkiemsanphamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timkiemsanphamActionPerformed

    private void btn_themsanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themsanphamActionPerformed
       try {
        // 1. Lấy dữ liệu từ form
        String ten = txt_tensanpham.getText().trim();
        String maSP = txt_masanpham.getText().trim();
        String moTa = txt_mota.getText().trim();
        int soLuong = Integer.parseInt(txt_soLuong.getText().trim());
        int trangThai = rdo_conban.isSelected() ? 1 : 0;

        // 2. Lấy ID từ ComboBox (đã ép kiểu từ object loadsanpham và hang)
        loadsanpham loai = (loadsanpham) cbo_loaisanpham.getSelectedItem();
      
        int loaiId = loai.getId();  
       hang selectedHang = (hang) cbo_hang.getSelectedItem();
       int hangId = selectedHang.getId();

        // 3. Tạo sản phẩm
        sanpham sp = new sanpham();
        sp.setTen(ten);
        sp.setMasp(maSP);
        sp.setMo_ta(moTa);
        sp.setLoai_san_pham_id(loaiId);
        sp.setHang_id(hangId);
        sp.setTrang_thai(trangThai);
        sp.setSo_luong(soLuong);

        daosp.insert(sp); // Thêm sản phẩm

        // 4. Lấy ID sản phẩm vừa thêm
        int sanPhamID = daosp.getIdByMaSP(maSP);

        // 5. Thêm serial và chi tiết sản phẩm mặc định
        for (int i = 0; i < soLuong; i++) {
            String maSerial = "SER" + System.currentTimeMillis() + i;

            serial s = new serial();
            s.setMa_serial(maSerial);
            s.setSan_pham_id(sanPhamID);
            s.setTrang_thai(0);
            serialdao.insert(s);

            int serialId = serialdao.getIdByMaSerial(maSerial);

            chitietsanpham ctsp = new chitietsanpham();
            ctsp.setSan_pham_id(sanPhamID);
            ctsp.setSerial_id(serialId);
            ctsp.setCpu_id(1); // mặc định, sau chỉnh sau
            ctsp.setRam_id(1);
            ctsp.setSsd_id(1);
            ctsp.setGpu_id(1);
            ctsp.setGia_ban(BigDecimal.ZERO);

            ctspDAO.insert(ctsp);
        }

        // 6. Lấy lại danh sách serial vừa thêm
        List<serial> dsSerial = serialdao.getBySanPhamId(sanPhamID);

        // 7. Mở JDialog nhập chi tiết phần cứng
        ChiTietSanPhamJDialog dialog = new ChiTietSanPhamJDialog(null, true, sanPhamID, dsSerial);
        dialog.setVisible(true);

        // 8. Load lại bảng
        loadTableSanPham();

        JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công!");

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi thêm sản phẩm: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_themsanphamActionPerformed

    private void tbl_bangsanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bangsanphamMouseClicked
        // TODO add your handling code here:
         int row = tbl_bangsanpham.getSelectedRow();
    if (row < 0) return;

    // Lấy tên sản phẩm từ cột 1 ("Tên Sản Phẩm")
    String tenSanPham = String.valueOf(tbl_bangsanpham.getValueAt(row, 1));

    // Gọi DAO để lấy chi tiết sản phẩm theo tên
    List<SanPhamChiTietViewModel> list = daosp.findAllView();

    DefaultTableModel model = (DefaultTableModel) tbl_bangDSSanPham.getModel();
    model.setRowCount(0);
    for (SanPhamChiTietViewModel ctsp : list) {
        if (ctsp.getTenSanPham() != null && ctsp.getTenSanPham().equals(tenSanPham)) {
            model.addRow(new Object[]{
                ctsp.getId(),
                ctsp.getTenSanPham(),
                ctsp.getCpu(),
                ctsp.getCard(),
                ctsp.getHang(),
                ctsp.getOcung(),
                ctsp.getRam(),
                ctsp.getSerial(),
                ctsp.getGiaBan(),
                ctsp.isTrangThai()? "Đang Bán" : " Đã Bán"
            });
        }
    }
      TableColumn idColumn = tbl_bangDSSanPham.getColumnModel().getColumn(0);
    idColumn.setMinWidth(0);
    idColumn.setMaxWidth(0);
    idColumn.setPreferredWidth(0);
    // Chuyển sang tab Chi Tiết Sản Phẩm
    jTabbedPane1.setSelectedIndex(1);
}//GEN-LAST:event_tbl_bangsanphamMouseClicked

    private void btn_themHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_themHangActionPerformed

    private void txt_idChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idChiTietActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idChiTietActionPerformed

    private void btn_quetqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quetqrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_quetqrActionPerformed

    private void btn_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lammoiActionPerformed

    private void tbl_bangDSSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bangDSSanPhamMouseClicked
        // TODO add your handling code here:
            int row = tbl_bangDSSanPham.getSelectedRow();
    if (row < 0) return;

    // 🟡 Lấy id của chi tiết sản phẩm (cột 0 thường là ID)
    String idChiTiet = String.valueOf(tbl_bangDSSanPham.getValueAt(row, 0));
    txt_idChiTiet.setText(idChiTiet); // <-- phải có 1 ô ẩn hoặc text lưu id để sửa

    // 🟢 Lấy dữ liệu còn lại
    String tenSP = String.valueOf(tbl_bangDSSanPham.getValueAt(row, 1));
    String cpu = String.valueOf(tbl_bangDSSanPham.getValueAt(row, 2));
    String card = String.valueOf(tbl_bangDSSanPham.getValueAt(row, 3));
    String hang = String.valueOf(tbl_bangDSSanPham.getValueAt(row, 4));
    String ocung = String.valueOf(tbl_bangDSSanPham.getValueAt(row, 5));
    String ram = String.valueOf(tbl_bangDSSanPham.getValueAt(row, 6));
    String serial = String.valueOf(tbl_bangDSSanPham.getValueAt(row, 7));
    String giaBan = String.valueOf(tbl_bangDSSanPham.getValueAt(row, 8));
    String trangThai = String.valueOf(tbl_bangDSSanPham.getValueAt(row, 9));

    // 🟢 Set dữ liệu lên form
    txt_tensp.setText(tenSP);
  // CPU
for (int i = 0; i < cbo_CPU.getItemCount(); i++) {
    Object item = cbo_CPU.getItemAt(i);
    if (item.toString().equals(cpu)) {
        cbo_CPU.setSelectedIndex(i);
        break;
    }
}
// Card
for (int i = 0; i < cbo_Card.getItemCount(); i++) {
    Object item = cbo_Card.getItemAt(i);
    if (item.toString().equals(card)) {
        cbo_Card.setSelectedIndex(i);
        break;
    }
}
// Hãng
for (int i = 0; i < cbo_Hang.getItemCount(); i++) {
    Object item = cbo_Hang.getItemAt(i);
    if (item.toString().equals(hang)) {
        cbo_Hang.setSelectedIndex(i);
        break;
    }
}
// Ổ cứng
for (int i = 0; i < cbo_OCung.getItemCount(); i++) {
    Object item = cbo_OCung.getItemAt(i);
    if (item.toString().equals(ocung)) {
        cbo_OCung.setSelectedIndex(i);
        break;
    }
}
// Ram
for (int i = 0; i < cbo_Ram.getItemCount(); i++) {
    Object item = cbo_Ram.getItemAt(i);
    if (item.toString().equals(ram)) {
        cbo_Ram.setSelectedIndex(i);
        break;
    }
}
    txt_serial.setText(serial);
    txt_gia.setText(giaBan);

    if ("Đang Bán".equalsIgnoreCase(trangThai)) {
        rdo_dangban.setSelected(true);
    } else {
        rdo_daban.setSelected(true);
    }
    }//GEN-LAST:event_tbl_bangDSSanPhamMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Export;
    private javax.swing.JButton btn_Import;
    private javax.swing.JButton btn_ThemCard;
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_lammoidssanpham;
    private javax.swing.JButton btn_quetqr;
    private javax.swing.JButton btn_suasanpham1;
    private javax.swing.JButton btn_themCPU;
    private javax.swing.JButton btn_themHang;
    private javax.swing.JButton btn_themOCung;
    private javax.swing.JButton btn_themRam;
    private javax.swing.JButton btn_themsanpham;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<cpu> cbo_CPU;
    private javax.swing.JComboBox<card> cbo_Card;
    private javax.swing.JComboBox<String> cbo_Hang;
    private javax.swing.JComboBox<ocung> cbo_OCung;
    private javax.swing.JComboBox<ram> cbo_Ram;
    private javax.swing.JComboBox<hang> cbo_hang;
    private javax.swing.JComboBox<loadsanpham> cbo_loaisanpham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rdo_conban;
    private javax.swing.JRadioButton rdo_daban;
    private javax.swing.JRadioButton rdo_dangban;
    private javax.swing.JRadioButton rdo_ngungkinhdoanh;
    private javax.swing.JTable tbl_bangDSSanPham;
    private javax.swing.JTable tbl_bangsanpham;
    private javax.swing.JTextField txt_gia;
    private javax.swing.JTextField txt_idChiTiet;
    private javax.swing.JTextField txt_masanpham;
    private javax.swing.JTextField txt_mota;
    private javax.swing.JTextField txt_serial;
    private javax.swing.JTextField txt_soLuong;
    private javax.swing.JTextField txt_tensanpham;
    private javax.swing.JTextField txt_tensp;
    private javax.swing.JTextField txt_timkiemdssanpham;
    private javax.swing.JTextField txt_timkiemsanpham;
    // End of variables declaration//GEN-END:variables
}
